version: '3.8'
services:
  mongo:
    image: mongo:6
    container_name: notify_me_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  app:
    build: .
    container_name: notify_me_app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/notify_me
      - YOUTUBE_API_KEYS=AIzaSyAPKnenr69H3dRFjQ8z9gK7cyvXm8zbRRo,https://developers.google.com/youtube/v3/docs/search/list
      - SEARCH_QUERY=cricket
      - FETCH_INTERVAL=10
      - PORT=3000
    depends_on:
      - mongo
volumes:
  mongo_data:
